config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: '/', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'signup', to: 'pages#signup'
  get 'contact-us', to: 'contacts#new', as: 'new_contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
	validates :comments, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new;
	end

	def create
		@contact = Contact.new(contact_params)

		if @contact.save
			name = params[:contact][:name]
			email = params[:contact][:email]
			body = params[:contact][:comments]

			flash[:success] = "Message Sent"
			redirect_to new_contacts_path
		else
			flash[:danger] = @contact.errors.full_messages.join(", ")
			redirect_to new_contacts_path
		end
	end

	private

		def contact_params
			params.require(:contact).permit(:name, :email, :comments)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
	def about

	end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
	def signup 

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<div class = "col-md-4 col-md-offset-4">
	<div class = "row">
		<div class = "well">
			<h3 class = "text-center">Contact Us</h3>
			<%= form_for "/contacts" do |f| %>
				<div class = "form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: 'form-control'%>
				</div>
				<div class = "form-group">
					<%= f.label :email_address %>
					<%= f.text_field :email_address, class: 'form-control'%>
				</div>
				<div class = "form-group">
					<%= f.label :comments %>
					<%= f.text_area :comments, class: 'form-control'%>
				</div>
					<%= f.submit 'Submit', class: 'btn btn-default' %>
			<%end %>
		</div>
	</div>
</div>

app/views/contacts/new.html.erb
<div class = "col-md-4 col-md-offset-4">
	<div class = "row">
		<div class = "well">
			<h3 class = "text-center">Contact Us</h3>
			<%= form_for @contact do |f| %>
				<div class = "form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: 'form-control'%>
				</div>
				<div class = "form-group">
					<%= f.label :email %>
					<%= f.text_field :email, class: 'form-control'%>
				</div>
				<div class = "form-group">
					<%= f.label :comments %>
					<%= f.text_area :comments, class: 'form-control'%>
				</div>
					<%= f.submit 'Submit', class: 'btn btn-default' %>
			<%end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitsound</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
  		<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    		<div class="navbar-header">
     		   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
       			  <span class="sr-only">Toggle navigation</span>
        		  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
      			<%= link_to '/', class:"navbar-brand" do %>
              <i class="fa fa-music" aria-hidden="true"></i>
      				FitSound
      			<%end%>
    		</div>
    		<div class = "collapse navbar-collapse" id=main-navbar-collapse>
    			<ul class = "nav navbar-nav navbar-right">
    				<li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", new_contacts_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
    			</ul>
    		</div>
    	</div>
    </nav>
    <div class = "container">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>

      <% end %>
    </div>

    <%= yield %>
  </body>
</html>